// source: data3.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var vox_pb = require('./vox_pb.js');
goog.object.extend(proto, vox_pb);
var svox_pb = require('./svox_pb.js');
goog.object.extend(proto, svox_pb);
goog.exportSymbol('proto.scan2cad.Data3', null, global);
goog.exportSymbol('proto.scan2cad.Data3.RepCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scan2cad.Data3 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.scan2cad.Data3.oneofGroups_);
};
goog.inherits(proto.scan2cad.Data3, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scan2cad.Data3.displayName = 'proto.scan2cad.Data3';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.scan2cad.Data3.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.scan2cad.Data3.RepCase = {
  REP_NOT_SET: 0,
  VOX: 1,
  SVOX: 2
};

/**
 * @return {proto.scan2cad.Data3.RepCase}
 */
proto.scan2cad.Data3.prototype.getRepCase = function() {
  return /** @type {proto.scan2cad.Data3.RepCase} */(jspb.Message.computeOneofCase(this, proto.scan2cad.Data3.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scan2cad.Data3.prototype.toObject = function(opt_includeInstance) {
  return proto.scan2cad.Data3.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scan2cad.Data3} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scan2cad.Data3.toObject = function(includeInstance, msg) {
  var f, obj = {
    vox: (f = msg.getVox()) && vox_pb.Vox.toObject(includeInstance, f),
    svox: (f = msg.getSvox()) && svox_pb.SVox.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scan2cad.Data3}
 */
proto.scan2cad.Data3.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scan2cad.Data3;
  return proto.scan2cad.Data3.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scan2cad.Data3} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scan2cad.Data3}
 */
proto.scan2cad.Data3.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new vox_pb.Vox;
      reader.readMessage(value,vox_pb.Vox.deserializeBinaryFromReader);
      msg.setVox(value);
      break;
    case 2:
      var value = new svox_pb.SVox;
      reader.readMessage(value,svox_pb.SVox.deserializeBinaryFromReader);
      msg.setSvox(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scan2cad.Data3.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scan2cad.Data3.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scan2cad.Data3} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scan2cad.Data3.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVox();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      vox_pb.Vox.serializeBinaryToWriter
    );
  }
  f = message.getSvox();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      svox_pb.SVox.serializeBinaryToWriter
    );
  }
};


/**
 * optional Vox vox = 1;
 * @return {?proto.scan2cad.Vox}
 */
proto.scan2cad.Data3.prototype.getVox = function() {
  return /** @type{?proto.scan2cad.Vox} */ (
    jspb.Message.getWrapperField(this, vox_pb.Vox, 1));
};


/**
 * @param {?proto.scan2cad.Vox|undefined} value
 * @return {!proto.scan2cad.Data3} returns this
*/
proto.scan2cad.Data3.prototype.setVox = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.scan2cad.Data3.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scan2cad.Data3} returns this
 */
proto.scan2cad.Data3.prototype.clearVox = function() {
  return this.setVox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scan2cad.Data3.prototype.hasVox = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SVox svox = 2;
 * @return {?proto.scan2cad.SVox}
 */
proto.scan2cad.Data3.prototype.getSvox = function() {
  return /** @type{?proto.scan2cad.SVox} */ (
    jspb.Message.getWrapperField(this, svox_pb.SVox, 2));
};


/**
 * @param {?proto.scan2cad.SVox|undefined} value
 * @return {!proto.scan2cad.Data3} returns this
*/
proto.scan2cad.Data3.prototype.setSvox = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.scan2cad.Data3.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scan2cad.Data3} returns this
 */
proto.scan2cad.Data3.prototype.clearSvox = function() {
  return this.setSvox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scan2cad.Data3.prototype.hasSvox = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.scan2cad);
